import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { strFromU8, unzipSync } from "npm:fflate@0.8.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

type IntakeStatus = "uploaded" | "processing" | "review_ready" | "completed" | "failed";
type ExtractionStatus = "not_started" | "queued" | "processing" | "completed" | "failed";

interface MedicalDocumentIntakeRow {
  id: string;
  user_id: string;
  file_name: string;
  file_type: string;
  file_size_bytes: number;
  intake_status: IntakeStatus;
  document_notes: string | null;
  candidate_count: number;
  storage_bucket?: string | null;
  storage_path?: string | null;
  content_sha256?: string | null;
  extraction_status?: ExtractionStatus;
  extraction_error?: string | null;
  extracted_text?: string | null;
  extracted_at?: string | null;
  page_count?: number | null;
  created_at: string;
  updated_at: string;
}

interface MedicalDocumentEvidenceSegmentInsert {
  user_id: string;
  document_intake_id: string;
  page_number: number | null;
  section_label: string | null;
  quoted_text: string;
  normalized_text: string | null;
  span_start: number | null;
  span_end: number | null;
  extractor_label: string | null;
  confidence_score: number | null;
}

interface ExtractionResponseBody {
  success: boolean;
  intake?: MedicalDocumentIntakeRow;
  extraction_supported?: boolean;
  message?: string | null;
  error?: string;
}

interface ExtractionResult {
  text: string;
  pageCount: number | null;
  extractorLabel: string;
  signalConfidence: number;
}

interface SectionChunk {
  label: string | null;
  text: string;
}

type MedicalFactCategory =
  | "diagnosis"
  | "suspected_condition"
  | "medication"
  | "surgery_procedure"
  | "allergy_intolerance"
  | "diet_guidance"
  | "red_flag_history";

type CandidateEvidenceKind =
  | "quote"
  | "summary"
  | "lab_value"
  | "medication_list"
  | "diagnosis_statement"
  | "procedure_statement";

interface CandidateMedicalFactRow {
  id: string;
  user_id: string;
  category: MedicalFactCategory;
  detail: Record<string, unknown>;
  extraction_source: string;
  source_document_id: string | null;
  extraction_confidence: number | null;
  extraction_notes: string | null;
  review_status: string;
  reviewed_at: string | null;
  promoted_fact_id: string | null;
  created_at: string;
  updated_at: string;
}

interface MedicalFactRow {
  id: string;
  user_id: string;
  category: MedicalFactCategory;
  confirmation_state: "confirmed" | "user_reported" | "candidate";
  detail: Record<string, unknown>;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

interface MedicalDocumentEvidenceSegmentRow {
  id: string;
  user_id: string;
  document_intake_id: string;
  page_number: number | null;
  section_label: string | null;
  quoted_text: string;
  normalized_text: string | null;
  span_start: number | null;
  span_end: number | null;
  extractor_label: string | null;
  confidence_score: number | null;
  created_at: string;
  updated_at: string;
}

interface AutoGeneratedCandidate {
  category: MedicalFactCategory;
  detail: Record<string, unknown>;
  extractionConfidence: number;
  extractionNotes: string;
  evidenceKind: CandidateEvidenceKind;
  evidenceSegmentId: string;
  pageNumber: number | null;
  citedText: string;
  evidenceConfidence: number | null;
}

interface CandidateGenerationSummary {
  pendingCreatedCount: number;
  mergedCreatedCount: number;
  conflictFlaggedCount: number;
  totalCount: number;
}

class ExtractionFailure extends Error {
  extractionSupported: boolean;

  constructor(message: string, extractionSupported: boolean) {
    super(message);
    this.name = "ExtractionFailure";
    this.extractionSupported = extractionSupported;
  }
}

const TEXT_FILE_TYPES = new Set(["text/plain"]);
const PDF_FILE_TYPES = new Set(["application/pdf"]);
const DOCX_FILE_TYPES = new Set([
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
]);
const LEGACY_DOC_FILE_TYPES = new Set(["application/msword"]);
const IMAGE_FILE_TYPES = new Set([
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/heic",
  "image/heif",
]);
const AUTO_SEGMENT_LABEL_PREFIX = "auto_segment:";
const AUTO_CANDIDATE_NOTE_PREFIX = "auto_generated:";
const AUTO_MERGE_NOTE_PREFIX = "auto_merge:";
const AUTO_CONFLICT_NOTE_PREFIX = "auto_conflict:";

const DIAGNOSIS_RULES: Array<{
  name: string;
  giRelevance: "primary" | "secondary" | "indirect";
  patterns: RegExp[];
}> = [
  {
    name: "Irritable bowel syndrome",
    giRelevance: "primary",
    patterns: [/\birritable bowel syndrome\b/i, /\bibs\b/i],
  },
  {
    name: "Crohn's disease",
    giRelevance: "primary",
    patterns: [/\bcrohn'?s disease\b/i],
  },
  {
    name: "Ulcerative colitis",
    giRelevance: "primary",
    patterns: [/\bulcerative colitis\b/i],
  },
  {
    name: "Inflammatory bowel disease",
    giRelevance: "primary",
    patterns: [/\binflammatory bowel disease\b/i, /\bibd\b/i],
  },
  {
    name: "Celiac disease",
    giRelevance: "primary",
    patterns: [/\bceliac disease\b/i, /\bcoeliac disease\b/i],
  },
  {
    name: "Gastroesophageal reflux disease",
    giRelevance: "secondary",
    patterns: [/\bgastroesophageal reflux disease\b/i, /\bgerd\b/i, /\bacid reflux\b/i],
  },
  {
    name: "Gastritis",
    giRelevance: "secondary",
    patterns: [/\bgastritis\b/i],
  },
  {
    name: "Gastroparesis",
    giRelevance: "primary",
    patterns: [/\bgastroparesis\b/i],
  },
  {
    name: "Diverticulitis",
    giRelevance: "primary",
    patterns: [/\bdiverticulitis\b/i],
  },
  {
    name: "Diverticulosis",
    giRelevance: "secondary",
    patterns: [/\bdiverticulosis\b/i],
  },
  {
    name: "Small intestinal bacterial overgrowth",
    giRelevance: "primary",
    patterns: [/\bsmall intestinal bacterial overgrowth\b/i, /\bsibo\b/i],
  },
  {
    name: "Functional dyspepsia",
    giRelevance: "secondary",
    patterns: [/\bfunctional dyspepsia\b/i],
  },
  {
    name: "Hemorrhoids",
    giRelevance: "secondary",
    patterns: [/\bhemorrhoids?\b/i, /\bhaemorrhoids?\b/i],
  },
];

const PROCEDURE_RULES: Array<{
  name: string;
  bodyRegion: string | null;
  giRelevance: "primary" | "secondary" | "indirect";
  patterns: RegExp[];
}> = [
  {
    name: "Colonoscopy",
    bodyRegion: "colon",
    giRelevance: "primary",
    patterns: [/\bcolonoscopy\b/i],
  },
  {
    name: "Upper endoscopy",
    bodyRegion: "upper GI tract",
    giRelevance: "primary",
    patterns: [/\bupper endoscopy\b/i, /\begd\b/i, /\besophagogastroduodenoscopy\b/i],
  },
  {
    name: "Flexible sigmoidoscopy",
    bodyRegion: "colon",
    giRelevance: "primary",
    patterns: [/\bflexible sigmoidoscopy\b/i, /\bsigmoidoscopy\b/i],
  },
  {
    name: "Appendectomy",
    bodyRegion: "appendix",
    giRelevance: "secondary",
    patterns: [/\bappendectomy\b/i],
  },
  {
    name: "Cholecystectomy",
    bodyRegion: "gallbladder",
    giRelevance: "secondary",
    patterns: [/\bcholecystectomy\b/i],
  },
  {
    name: "Bowel resection",
    bodyRegion: "bowel",
    giRelevance: "primary",
    patterns: [/\bbowel resection\b/i, /\bsmall bowel resection\b/i],
  },
  {
    name: "Colectomy",
    bodyRegion: "colon",
    giRelevance: "primary",
    patterns: [/\bcolectomy\b/i],
  },
  {
    name: "Polypectomy",
    bodyRegion: "colon",
    giRelevance: "secondary",
    patterns: [/\bpolypectomy\b/i],
  },
  {
    name: "Hemorrhoidectomy",
    bodyRegion: "rectum",
    giRelevance: "secondary",
    patterns: [/\bhemorrhoidectomy\b/i],
  },
];

const DIET_GUIDANCE_RULES: Array<{
  name: string;
  patterns: RegExp[];
}> = [
  { name: "Low-FODMAP", patterns: [/\blow[- ]fodmap\b/i] },
  { name: "Gluten-free", patterns: [/\bgluten[- ]free\b/i] },
  { name: "Lactose-free", patterns: [/\blactose[- ]free\b/i] },
  { name: "Dairy-free", patterns: [/\bdairy[- ]free\b/i] },
  { name: "Elimination diet", patterns: [/\belimination diet\b/i] },
  { name: "Low-residue", patterns: [/\blow[- ]residue\b/i] },
  { name: "Clear liquid diet", patterns: [/\bclear liquid diet\b/i] },
  { name: "BRAT diet", patterns: [/\bbrat diet\b/i] },
  { name: "High-fiber diet", patterns: [/\bhigh[- ]fiber diet\b/i, /\bincrease fiber\b/i] },
  { name: "Low-fat diet", patterns: [/\blow[- ]fat diet\b/i] },
  { name: "Bland diet", patterns: [/\bbland diet\b/i] },
];

const RED_FLAG_RULES: Array<{
  name: string;
  patterns: RegExp[];
}> = [
  {
    name: "Rectal bleeding",
    patterns: [/\brectal bleeding\b/i, /\bblood in stool\b/i, /\bhematochezia\b/i, /\bmelena\b/i],
  },
  {
    name: "Unexplained weight loss",
    patterns: [/\bunexplained weight loss\b/i, /\bweight loss\b/i],
  },
  {
    name: "Anemia",
    patterns: [/\banemia\b/i, /\banaemia\b/i],
  },
  {
    name: "Bowel obstruction",
    patterns: [/\bbowel obstruction\b/i, /\bintestinal obstruction\b/i],
  },
  {
    name: "GI bleeding",
    patterns: [/\bgi bleed(?:ing)?\b/i, /\bgastrointestinal bleed(?:ing)?\b/i],
  },
  {
    name: "Vomiting blood",
    patterns: [/\bhematemesis\b/i, /\bvomiting blood\b/i],
  },
  {
    name: "Nocturnal diarrhea",
    patterns: [/\bnocturnal diarrhea\b/i],
  },
];

const GI_SYMPTOM_TERMS: Array<{ label: string; regex: RegExp }> = [
  { label: "bloating", regex: /\bbloating\b/i },
  { label: "cramping", regex: /\bcramp(?:ing|s)?\b/i },
  { label: "diarrhea", regex: /\bdiarrh(?:ea|oea)\b/i },
  { label: "constipation", regex: /\bconstipation\b/i },
  { label: "nausea", regex: /\bnausea\b/i },
  { label: "vomiting", regex: /\bvomit(?:ing)?\b/i },
  { label: "abdominal pain", regex: /\babdominal pain\b/i },
  { label: "gas", regex: /\bgas\b/i },
  { label: "reflux", regex: /\breflux\b/i },
];

const MEDICATION_FREQUENCY_REGEX =
  /\b(once daily|twice daily|three times daily|daily|bid|tid|qid|qhs|q\d+h|every \d+\s*(?:hours?|hrs?)|weekly|monthly|as needed|prn|before meals?|after meals?|with meals?|at bedtime)\b/i;

const GI_RELEVANT_MEDICATION_HINTS = [
  /\bomeprazole\b/i,
  /\bpantoprazole\b/i,
  /\blansoprazole\b/i,
  /\besomeprazole\b/i,
  /\bloperamide\b/i,
  /\bimodium\b/i,
  /\bsenna\b/i,
  /\bbisacodyl\b/i,
  /\bmiralax\b/i,
  /\bpolyethylene glycol\b/i,
  /\bmagnesium\b/i,
  /\biron\b/i,
  /\bmetformin\b/i,
  /\bmesalamine\b/i,
  /\brifaximin\b/i,
  /\bantibiotic\b/i,
];

const GENERIC_MEDICATION_STOP_WORDS = new Set([
  "medication",
  "medications",
  "medicine",
  "medicines",
  "dose",
  "dosage",
  "tablet",
  "tablets",
  "capsule",
  "capsules",
  "instructions",
  "history",
  "current",
  "home",
  "discharge",
  "take",
  "takes",
  "taking",
  "continue",
  "continued",
  "stop",
  "stopped",
]);

function jsonResponse(status: number, body: ExtractionResponseBody): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

async function updateIntake(
  supabaseAdmin: ReturnType<typeof createClient>,
  intakeId: string,
  updates: Partial<MedicalDocumentIntakeRow>
): Promise<MedicalDocumentIntakeRow> {
  const { data, error } = await supabaseAdmin
    .from("medical_document_intakes")
    .update({
      ...updates,
      updated_at: new Date().toISOString(),
    })
    .eq("id", intakeId)
    .select("*")
    .maybeSingle();

  if (error) throw error;
  return data as MedicalDocumentIntakeRow;
}

function getLowerFileName(intake: MedicalDocumentIntakeRow): string {
  return intake.file_name.toLowerCase();
}

function isTextIntake(intake: MedicalDocumentIntakeRow): boolean {
  return TEXT_FILE_TYPES.has(intake.file_type) || getLowerFileName(intake).endsWith(".txt");
}

function isPdfIntake(intake: MedicalDocumentIntakeRow): boolean {
  return PDF_FILE_TYPES.has(intake.file_type) || getLowerFileName(intake).endsWith(".pdf");
}

function isDocxIntake(intake: MedicalDocumentIntakeRow): boolean {
  return DOCX_FILE_TYPES.has(intake.file_type) || getLowerFileName(intake).endsWith(".docx");
}

function isLegacyDocIntake(intake: MedicalDocumentIntakeRow): boolean {
  return LEGACY_DOC_FILE_TYPES.has(intake.file_type) || getLowerFileName(intake).endsWith(".doc");
}

function isImageIntake(intake: MedicalDocumentIntakeRow): boolean {
  const lowerName = getLowerFileName(intake);
  return (
    IMAGE_FILE_TYPES.has(intake.file_type) ||
    [".jpg", ".jpeg", ".png", ".webp", ".heic", ".heif"].some((extension) =>
      lowerName.endsWith(extension)
    )
  );
}

function normalizeExtractedText(text: string): string {
  return text
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/[ \t]{2,}/g, " ")
    .trim();
}

function normalizeSectionLabel(value: string): string | null {
  const cleaned = value
    .replace(/[:\-\u2013\u2014]\s*$/, "")
    .replace(/\s+/g, " ")
    .trim();

  if (!cleaned) return null;
  if (cleaned.length > 80) return null;

  return cleaned;
}

function isLikelyHeading(line: string): boolean {
  const trimmed = line.trim();
  if (trimmed.length < 3 || trimmed.length > 80) return false;
  if (/[.!?]$/.test(trimmed)) return false;

  const words = trimmed.split(/\s+/);
  if (words.length > 8) return false;

  const alphaChars = trimmed.replace(/[^A-Za-z]/g, "");
  if (alphaChars.length === 0) return false;

  const uppercaseRatio =
    alphaChars.split("").filter((char) => char === char.toUpperCase()).length / alphaChars.length;

  return uppercaseRatio > 0.7 || /:$/.test(trimmed);
}

function splitIntoSections(text: string): SectionChunk[] {
  const paragraphs = text
    .split(/\n{2,}/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean);

  if (paragraphs.length === 0) {
    return [];
  }

  const sections: SectionChunk[] = [];
  let currentLabel: string | null = null;
  let currentParagraphs: string[] = [];

  const flush = () => {
    if (currentParagraphs.length === 0) return;
    sections.push({
      label: currentLabel,
      text: currentParagraphs.join("\n\n").trim(),
    });
    currentParagraphs = [];
  };

  for (const paragraph of paragraphs) {
    const lines = paragraph.split("\n").map((line) => line.trim()).filter(Boolean);
    const firstLine = lines[0] ?? "";

    if (isLikelyHeading(firstLine)) {
      flush();
      currentLabel = normalizeSectionLabel(firstLine);
      const remainder = lines.slice(1).join(" ").trim();
      if (remainder) {
        currentParagraphs.push(remainder);
      }
      continue;
    }

    currentParagraphs.push(paragraph);
  }

  flush();

  if (sections.length === 0) {
    return [{ label: null, text }];
  }

  return sections;
}

function splitTextIntoEvidenceChunks(text: string, maxLength = 650): string[] {
  const paragraphs = text
    .split(/\n{2,}/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean);

  if (paragraphs.length === 0) return [];

  const chunks: string[] = [];
  let current = "";

  const pushCurrent = () => {
    const normalized = normalizeExtractedText(current);
    if (normalized) {
      chunks.push(normalized);
    }
    current = "";
  };

  for (const paragraph of paragraphs) {
    if (!current) {
      current = paragraph;
      continue;
    }

    const candidate = `${current}\n\n${paragraph}`;
    if (candidate.length <= maxLength) {
      current = candidate;
      continue;
    }

    pushCurrent();

    if (paragraph.length <= maxLength) {
      current = paragraph;
      continue;
    }

    const sentences = paragraph.match(/[^.!?\n]+[.!?]?/g)?.map((sentence) => sentence.trim()).filter(Boolean)
      ?? [paragraph];

    for (const sentence of sentences) {
      if (!current) {
        current = sentence;
        continue;
      }

      const sentenceCandidate = `${current} ${sentence}`.trim();
      if (sentenceCandidate.length <= maxLength) {
        current = sentenceCandidate;
      } else {
        pushCurrent();
        current = sentence;
      }
    }
  }

  pushCurrent();
  return chunks;
}

function buildEvidenceSegments(
  intake: MedicalDocumentIntakeRow,
  extraction: ExtractionResult
): MedicalDocumentEvidenceSegmentInsert[] {
  const sections = splitIntoSections(extraction.text);
  const fullText = extraction.text;
  let searchStart = 0;
  const pageNumberForAll = extraction.pageCount === 1 ? 1 : null;

  const segments: MedicalDocumentEvidenceSegmentInsert[] = [];

  for (const section of sections) {
    const chunks = splitTextIntoEvidenceChunks(section.text);

    for (const chunk of chunks) {
      const spanStart = fullText.indexOf(chunk, searchStart);
      const resolvedSpanStart = spanStart >= 0 ? spanStart : fullText.indexOf(chunk);
      const spanEnd =
        resolvedSpanStart >= 0 ? resolvedSpanStart + chunk.length : null;

      if (resolvedSpanStart >= 0) {
        searchStart = resolvedSpanStart + chunk.length;
      }

      segments.push({
        user_id: intake.user_id,
        document_intake_id: intake.id,
        page_number: pageNumberForAll,
        section_label: section.label,
        quoted_text: chunk,
        normalized_text: chunk,
        span_start: resolvedSpanStart >= 0 ? resolvedSpanStart : null,
        span_end: spanEnd,
        extractor_label: `${AUTO_SEGMENT_LABEL_PREFIX}${extraction.extractorLabel}`,
        confidence_score: extraction.signalConfidence,
      });
    }
  }

  return segments;
}

async function persistEvidenceSegments(
  supabaseAdmin: ReturnType<typeof createClient>,
  intake: MedicalDocumentIntakeRow,
  extraction: ExtractionResult
): Promise<number> {
  const { data: existingSegments, error: existingError } = await supabaseAdmin
    .from("medical_document_evidence_segments")
    .select("id")
    .eq("document_intake_id", intake.id)
    .eq("user_id", intake.user_id)
    .like("extractor_label", `${AUTO_SEGMENT_LABEL_PREFIX}%`);

  if (existingError) throw existingError;

  if ((existingSegments?.length ?? 0) > 0) {
    return existingSegments?.length ?? 0;
  }

  const inserts = buildEvidenceSegments(intake, extraction);
  if (inserts.length === 0) {
    return 0;
  }

  const { error: insertError } = await supabaseAdmin
    .from("medical_document_evidence_segments")
    .insert(inserts);

  if (insertError) throw insertError;
  return inserts.length;
}

function inferCandidateEvidenceKind(category: MedicalFactCategory): CandidateEvidenceKind {
  switch (category) {
    case "diagnosis":
      return "diagnosis_statement";
    case "medication":
      return "medication_list";
    case "surgery_procedure":
      return "procedure_statement";
    default:
      return "summary";
  }
}

function stableStringify(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map((item) => stableStringify(item)).join(",")}]`;
  }

  if (value && typeof value === "object") {
    const record = value as Record<string, unknown>;
    const keys = Object.keys(record).sort();
    return `{${keys.map((key) => `${JSON.stringify(key)}:${stableStringify(record[key])}`).join(",")}}`;
  }

  return JSON.stringify(value);
}

function normalizeStringList(values: string[]): string[] {
  const seen = new Set<string>();
  const normalized: string[] = [];

  for (const value of values) {
    const cleaned = value.replace(/\s+/g, " ").trim();
    if (!cleaned) continue;

    const key = cleaned.toLowerCase();
    if (seen.has(key)) continue;

    seen.add(key);
    normalized.push(cleaned);
  }

  return normalized;
}

function normalizeDetailForSignature(detail: Record<string, unknown>): Record<string, unknown> {
  const normalized: Record<string, unknown> = {};

  for (const [key, rawValue] of Object.entries(detail)) {
    if (Array.isArray(rawValue)) {
      const normalizedArray = normalizeStringList(
        rawValue.map((value) => String(value))
      ).sort((left, right) => left.localeCompare(right));
      normalized[key] = normalizedArray;
      continue;
    }

    if (typeof rawValue === "string") {
      normalized[key] = rawValue.replace(/\s+/g, " ").trim();
      continue;
    }

    normalized[key] = rawValue;
  }

  return normalized;
}

function buildCandidateSignature(
  category: MedicalFactCategory,
  detail: Record<string, unknown>
): string {
  return `${category}:${stableStringify(normalizeDetailForSignature(detail))}`;
}

function normalizeIdentityValue(value: unknown): string | null {
  if (typeof value !== "string") return null;

  const cleaned = value
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();

  return cleaned || null;
}

function buildCandidateMergeKey(
  category: MedicalFactCategory,
  detail: Record<string, unknown>
): string | null {
  switch (category) {
    case "diagnosis":
    case "suspected_condition": {
      const name = normalizeIdentityValue(detail.condition_name);
      return name ? `${category}:${name}` : null;
    }
    case "medication": {
      const medicationName = normalizeIdentityValue(detail.medication_name);
      return medicationName ? `${category}:${medicationName}` : null;
    }
    case "surgery_procedure": {
      const procedureName = normalizeIdentityValue(detail.procedure_name);
      return procedureName ? `${category}:${procedureName}` : null;
    }
    case "allergy_intolerance": {
      const substance = normalizeIdentityValue(detail.substance);
      const reactionType = normalizeIdentityValue(detail.reaction_type);
      return substance
        ? `${category}:${substance}:${reactionType ?? "unknown"}`
        : null;
    }
    case "diet_guidance": {
      const guidanceType = normalizeIdentityValue(detail.guidance_type);
      return guidanceType ? `${category}:${guidanceType}` : null;
    }
    case "red_flag_history": {
      const flagType = normalizeIdentityValue(detail.flag_type);
      return flagType ? `${category}:${flagType}` : null;
    }
    default:
      return null;
  }
}

function buildCandidateDisplayLabel(
  category: MedicalFactCategory,
  detail: Record<string, unknown>
): string {
  switch (category) {
    case "diagnosis":
    case "suspected_condition":
      return String(detail.condition_name ?? "condition");
    case "medication":
      return String(detail.medication_name ?? "medication");
    case "surgery_procedure":
      return String(detail.procedure_name ?? "procedure");
    case "allergy_intolerance":
      return String(detail.substance ?? "allergy or intolerance");
    case "diet_guidance":
      return String(detail.guidance_type ?? "diet guidance");
    case "red_flag_history":
      return String(detail.flag_type ?? "red-flag history");
    default:
      return category.replace(/_/g, " ");
  }
}

function appendStructuredCandidateNote(
  baseNote: string,
  prefix: string,
  message: string
): string {
  const trimmedBase = baseNote.trim();
  const trimmedMessage = `${prefix} ${message}`.trim();

  if (!trimmedBase) return trimmedMessage;
  if (trimmedBase.includes(trimmedMessage)) return trimmedBase;

  return `${trimmedBase}\n${trimmedMessage}`;
}

function createMergeResolutionNote(
  category: MedicalFactCategory,
  detail: Record<string, unknown>,
  targetKind: "active_fact" | "pending_candidate"
): string {
  const label = buildCandidateDisplayLabel(category, detail);

  if (targetKind === "active_fact") {
    return `This extracted detail matched existing active context for "${label}" and was merged instead of creating another review item.`;
  }

  return `This extracted detail corroborated an existing pending review item for "${label}" and was merged instead of creating another queue item.`;
}

function createConflictResolutionNote(
  category: MedicalFactCategory,
  detail: Record<string, unknown>,
  targetKind: "active_fact" | "pending_candidate"
): string {
  const label = buildCandidateDisplayLabel(category, detail);

  if (targetKind === "active_fact") {
    return `Potential overlap was found with existing active context for "${label}", but the extracted details do not match exactly. Review before accepting.`;
  }

  return `Potential overlap was found with another pending review item for "${label}", but the extracted details do not match exactly. Review before accepting.`;
}

function addToLookupMap<T>(map: Map<string, T[]>, key: string | null, value: T): void {
  if (!key) return;
  const existing = map.get(key) ?? [];
  existing.push(value);
  map.set(key, existing);
}

function buildCandidateSummaryMessage(
  summary: CandidateGenerationSummary,
  emptyMessage: string
): string {
  const parts: string[] = [];

  if (summary.pendingCreatedCount > 0) {
    parts.push(
      `${summary.pendingCreatedCount} reviewable candidate${summary.pendingCreatedCount === 1 ? "" : "s"} generated`
    );
  }

  if (summary.mergedCreatedCount > 0) {
    parts.push(
      `${summary.mergedCreatedCount} overlapping detail${summary.mergedCreatedCount === 1 ? "" : "s"} merged into existing evidence`
    );
  }

  if (summary.conflictFlaggedCount > 0) {
    parts.push(
      `${summary.conflictFlaggedCount} overlapping detail${summary.conflictFlaggedCount === 1 ? "" : "s"} flagged for conflict review`
    );
  }

  if (parts.length === 0) {
    return emptyMessage;
  }

  const [first, ...rest] = parts;
  const sentence = [first.charAt(0).toUpperCase() + first.slice(1), ...rest].join("; ");
  return `${sentence}.`;
}

function clampConfidence(value: number): number {
  if (Number.isNaN(value)) return 0.5;
  if (value < 0) return 0;
  if (value > 1) return 1;
  return Number(value.toFixed(2));
}

function mergeCandidateConfidence(
  segmentConfidence: number | null | undefined,
  candidateBase: number
): number {
  return clampConfidence(
    Math.min(0.98, Math.max(segmentConfidence ?? 0, candidateBase))
  );
}

function toDisplayText(value: string): string {
  const cleaned = value.replace(/\s+/g, " ").trim();
  if (!cleaned) return "";

  return cleaned
    .split(" ")
    .map((token) => {
      if (token.length <= 4 && token === token.toUpperCase()) {
        return token;
      }

      const lower = token.toLowerCase();
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join(" ");
}

function cleanListToken(value: string): string {
  return value
    .replace(/^[•*\-\d.)\s]+/, "")
    .replace(/\(.*?\)/g, "")
    .replace(/\b(?:reaction|causes?|symptoms?)\b.*$/i, "")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/[,:;.\-]+$/, "")
    .trim();
}

function splitListValues(value: string): string[] {
  return normalizeStringList(
    value
      .replace(/\b(?:foods?\s+such\s+as|including|include|avoid|avoiding|restrict|restricted|limit|limiting)\b/gi, "")
      .split(/,|;|\band\b/gi)
      .map((token) => cleanListToken(token))
      .filter(Boolean)
  );
}

function extractFirstDate(text: string): string | null {
  const candidates: string[] = [];
  const slashMatch = text.match(/\b\d{1,2}\/\d{1,2}\/\d{2,4}\b/);
  if (slashMatch) candidates.push(slashMatch[0]);

  const isoMatch = text.match(/\b\d{4}-\d{2}-\d{2}\b/);
  if (isoMatch) candidates.push(isoMatch[0]);

  const monthMatch = text.match(
    /\b(?:jan|january|feb|february|mar|march|apr|april|may|jun|june|jul|july|aug|august|sep|sept|september|oct|october|nov|november|dec|december)\s+\d{1,2},?\s+\d{4}\b/i,
  );
  if (monthMatch) candidates.push(monthMatch[0]);

  for (const candidate of candidates) {
    const parsed = new Date(candidate);
    if (Number.isNaN(parsed.getTime())) continue;
    return parsed.toISOString().slice(0, 10);
  }

  return null;
}

function containsNegationNearMatch(textLower: string, matchIndex: number): boolean {
  const prefix = textLower.slice(Math.max(0, matchIndex - 40), matchIndex);
  return /\b(?:no|denies|denied|without|negative for|free of|not on|no evidence of|rule out|ruled out)\b/i
    .test(prefix);
}

function extractSentenceContaining(text: string, pattern: RegExp): string {
  const sentences = text
    .split(/(?<=[.!?])\s+/)
    .map((sentence) => sentence.trim())
    .filter(Boolean);

  for (const sentence of sentences) {
    if (pattern.test(sentence)) {
      return sentence;
    }
  }

  return normalizeExtractedText(text).slice(0, 220);
}

function extractGiSymptoms(text: string): string[] | null {
  const matches = GI_SYMPTOM_TERMS
    .filter((entry) => entry.regex.test(text))
    .map((entry) => entry.label);

  return matches.length > 0 ? normalizeStringList(matches) : null;
}

function buildAutoCandidateNote(
  sectionLabel: string | null,
  reason: string
): string {
  return `${AUTO_CANDIDATE_NOTE_PREFIX} ${reason}${sectionLabel ? ` from section "${sectionLabel}"` : " from extracted document text"}. Review against the cited evidence before accepting.`;
}

function buildDiagnosisCandidatesFromSegment(
  segment: MedicalDocumentEvidenceSegmentRow
): AutoGeneratedCandidate[] {
  const candidates: AutoGeneratedCandidate[] = [];
  const text = segment.normalized_text || segment.quoted_text;
  const textLower = text.toLowerCase();
  const labelLower = segment.section_label?.toLowerCase() ?? "";
  const diagnosisContext =
    /diagnos|assessment|impression|problem list|history|past medical history|pmh/.test(labelLower) ||
    /\b(?:diagnosed with|history of|assessment|impression|problem list|past medical history)\b/i.test(text);

  for (const rule of DIAGNOSIS_RULES) {
    for (const pattern of rule.patterns) {
      const match = pattern.exec(text);
      if (!match) continue;

      const matchIndex = match.index ?? textLower.indexOf(match[0].toLowerCase());
      if (matchIndex >= 0 && containsNegationNearMatch(textLower, matchIndex)) {
        continue;
      }

      if (!diagnosisContext) {
        continue;
      }

      if (/\b(?:possible|suspected|concern for|rule out|r\/o)\b/i.test(text)) {
        continue;
      }

      const severityMatch = text.match(/\b(mild|moderate|severe)\b/i);
      candidates.push({
        category: "diagnosis",
        detail: {
          condition_name: rule.name,
          icd_code: null,
          diagnosed_date: extractFirstDate(text),
          diagnosing_provider: null,
          severity: severityMatch ? severityMatch[1].toLowerCase() : null,
          gi_relevance: rule.giRelevance,
        },
        extractionConfidence: mergeCandidateConfidence(
          segment.confidence_score,
          labelLower ? 0.88 : 0.8,
        ),
        extractionNotes: buildAutoCandidateNote(
          segment.section_label,
          `Matched diagnosis pattern "${rule.name}"`
        ),
        evidenceKind: inferCandidateEvidenceKind("diagnosis"),
        evidenceSegmentId: segment.id,
        pageNumber: segment.page_number,
        citedText: extractSentenceContaining(text, pattern),
        evidenceConfidence: segment.confidence_score,
      });
      break;
    }
  }

  return candidates;
}

function buildProcedureCandidatesFromSegment(
  segment: MedicalDocumentEvidenceSegmentRow
): AutoGeneratedCandidate[] {
  const candidates: AutoGeneratedCandidate[] = [];
  const text = segment.normalized_text || segment.quoted_text;
  const textLower = text.toLowerCase();
  const labelLower = segment.section_label?.toLowerCase() ?? "";
  const procedureContext =
    /procedure|surgery|operative|past surgical history|psh/.test(labelLower) ||
    /\b(?:underwent|status post|s\/p|procedure|surgery|operative)\b/i.test(text);

  for (const rule of PROCEDURE_RULES) {
    for (const pattern of rule.patterns) {
      const match = pattern.exec(text);
      if (!match) continue;

      const matchIndex = match.index ?? textLower.indexOf(match[0].toLowerCase());
      if (matchIndex >= 0 && containsNegationNearMatch(textLower, matchIndex)) {
        continue;
      }

      if (!procedureContext && !pattern.test(labelLower)) {
        continue;
      }

      const complicationMatch = text.match(
        /\b(?:complication[s]?|complicated by|with complication of)\s*[:\-]?\s*([^.;\n]+)/i,
      );

      candidates.push({
        category: "surgery_procedure",
        detail: {
          procedure_name: rule.name,
          procedure_date: extractFirstDate(text),
          body_region: rule.bodyRegion,
          gi_relevance: rule.giRelevance,
          complications: complicationMatch ? cleanListToken(complicationMatch[1]) : null,
        },
        extractionConfidence: mergeCandidateConfidence(
          segment.confidence_score,
          procedureContext ? 0.86 : 0.78,
        ),
        extractionNotes: buildAutoCandidateNote(
          segment.section_label,
          `Matched procedure pattern "${rule.name}"`
        ),
        evidenceKind: inferCandidateEvidenceKind("surgery_procedure"),
        evidenceSegmentId: segment.id,
        pageNumber: segment.page_number,
        citedText: extractSentenceContaining(text, pattern),
        evidenceConfidence: segment.confidence_score,
      });
      break;
    }
  }

  return candidates;
}

function buildAllergyCandidatesFromSegment(
  segment: MedicalDocumentEvidenceSegmentRow
): AutoGeneratedCandidate[] {
  const text = segment.normalized_text || segment.quoted_text;
  const textLower = text.toLowerCase();
  const labelLower = segment.section_label?.toLowerCase() ?? "";

  if (/\b(?:nkda|no known drug allergies|no known allergies)\b/i.test(text)) {
    return [];
  }

  const contextMatch =
    /allerg|intoleran|sensitivit/.test(labelLower) ||
    /\b(?:allergies|allergy|allergic to|intolerant to|intolerance|sensitivity|sensitivities)\b/i
      .test(text);

  if (!contextMatch) {
    return [];
  }

  const extractedGroups: Array<{ reactionType: "allergy" | "intolerance" | "sensitivity"; values: string[] }> =
    [];

  const lineMatches = Array.from(
    text.matchAll(
      /\b(allerg(?:y|ies)|allergic to|intolerances?|intolerant to|sensitivities?|sensitive to)\b\s*[:\-]?\s*([^.;\n]+)/gi,
    ),
  );

  for (const match of lineMatches) {
    const trigger = match[1].toLowerCase();
    const values = splitListValues(match[2]);
    if (values.length === 0) continue;

    const reactionType = trigger.includes("intoler")
      ? "intolerance"
      : trigger.includes("sensit")
        ? "sensitivity"
        : "allergy";

    extractedGroups.push({ reactionType, values });
  }

  if (extractedGroups.length === 0 && /allerg|intoleran|sensitivit/.test(labelLower)) {
    extractedGroups.push({
      reactionType: labelLower.includes("intoleran")
        ? "intolerance"
        : labelLower.includes("sensit")
          ? "sensitivity"
          : "allergy",
      values: splitListValues(text),
    });
  }

  const candidates: AutoGeneratedCandidate[] = [];
  const giSymptoms = extractGiSymptoms(text);

  for (const group of extractedGroups) {
    for (const rawValue of group.values) {
      const substance = toDisplayText(cleanListToken(rawValue));
      if (!substance || /^(none|n\/a|unknown)$/i.test(substance)) {
        continue;
      }

      candidates.push({
        category: "allergy_intolerance",
        detail: {
          substance,
          reaction_type: group.reactionType,
          severity: null,
          confirmed_by_testing: /\bconfirmed\b.*\btest/i.test(text),
          gi_symptoms: giSymptoms,
        },
        extractionConfidence: mergeCandidateConfidence(segment.confidence_score, 0.88),
        extractionNotes: buildAutoCandidateNote(
          segment.section_label,
          `Matched ${group.reactionType} evidence for "${substance}"`
        ),
        evidenceKind: inferCandidateEvidenceKind("allergy_intolerance"),
        evidenceSegmentId: segment.id,
        pageNumber: segment.page_number,
        citedText: text,
        evidenceConfidence: segment.confidence_score,
      });
    }
  }

  return candidates;
}

function buildDietGuidanceCandidatesFromSegment(
  segment: MedicalDocumentEvidenceSegmentRow
): AutoGeneratedCandidate[] {
  const text = segment.normalized_text || segment.quoted_text;
  const labelLower = segment.section_label?.toLowerCase() ?? "";
  const dietContext =
    /diet|nutrition|nutrition plan|dietary/.test(labelLower) ||
    /\b(?:diet|nutrition|dietary|avoid|restrict|eliminate|low[- ]fodmap|gluten[- ]free|lactose[- ]free)\b/i
      .test(text);

  if (!dietContext) {
    return [];
  }

  const foodsToAvoid = splitListValues(
    text.match(/\b(?:avoid|avoiding|restrict|restricted|eliminate|limit)\b\s*[:\-]?\s*([^.;\n]+)/i)?.[1] ?? "",
  );
  const foodsToInclude = splitListValues(
    text.match(/\b(?:include|including|encourage|increase)\b\s*[:\-]?\s*([^.;\n]+)/i)?.[1] ?? "",
  );

  const candidates: AutoGeneratedCandidate[] = [];

  for (const rule of DIET_GUIDANCE_RULES) {
    if (!rule.patterns.some((pattern) => pattern.test(text) || pattern.test(labelLower))) {
      continue;
    }

    candidates.push({
      category: "diet_guidance",
        detail: {
          guidance_type: rule.name,
          prescribed_by: null,
          prescribed_date: extractFirstDate(text),
          foods_to_avoid: foodsToAvoid.length > 0 ? foodsToAvoid : null,
          foods_to_include: foodsToInclude.length > 0 ? foodsToInclude : null,
          rationale: extractSentenceContaining(text, rule.patterns[0]),
          is_current: !/\b(?:completed|ended|former|previously)\b/i.test(text),
        },
        extractionConfidence: mergeCandidateConfidence(segment.confidence_score, 0.82),
      extractionNotes: buildAutoCandidateNote(
        segment.section_label,
        `Matched diet guidance "${rule.name}"`
      ),
      evidenceKind: inferCandidateEvidenceKind("diet_guidance"),
      evidenceSegmentId: segment.id,
      pageNumber: segment.page_number,
      citedText: text,
      evidenceConfidence: segment.confidence_score,
    });
  }

  return candidates;
}

function buildRedFlagCandidatesFromSegment(
  segment: MedicalDocumentEvidenceSegmentRow
): AutoGeneratedCandidate[] {
  const candidates: AutoGeneratedCandidate[] = [];
  const text = segment.normalized_text || segment.quoted_text;
  const textLower = text.toLowerCase();

  for (const rule of RED_FLAG_RULES) {
    for (const pattern of rule.patterns) {
      const match = pattern.exec(text);
      if (!match) continue;

      const matchIndex = match.index ?? textLower.indexOf(match[0].toLowerCase());
      if (matchIndex >= 0 && containsNegationNearMatch(textLower, matchIndex)) {
        continue;
      }

      candidates.push({
        category: "red_flag_history",
        detail: {
          flag_type: rule.name,
          description: extractSentenceContaining(text, pattern),
          occurrence_date: extractFirstDate(text),
          resolved: /\b(?:resolved|improved|treated|addressed)\b/i.test(text),
          clinical_action_taken: null,
        },
        extractionConfidence: mergeCandidateConfidence(segment.confidence_score, 0.78),
        extractionNotes: buildAutoCandidateNote(
          segment.section_label,
          `Matched red-flag history "${rule.name}"`
        ),
        evidenceKind: inferCandidateEvidenceKind("red_flag_history"),
        evidenceSegmentId: segment.id,
        pageNumber: segment.page_number,
        citedText: extractSentenceContaining(text, pattern),
        evidenceConfidence: segment.confidence_score,
      });
      break;
    }
  }

  return candidates;
}

function splitMedicationLines(text: string): string[] {
  return normalizeStringList(
    text
      .split(/\n|;|•/g)
      .map((line) => line.trim())
      .filter((line) => line.length > 2),
  );
}

function deriveMedicationName(line: string, dosage: string | null): string {
  let candidate = line
    .replace(/^[•*\-\d.)\s]+/, "")
    .replace(/^(?:medications?|home meds?|discharge meds?|current meds?)\s*[:\-]?\s*/i, "")
    .replace(/^(?:take|takes|taking|continue|continued)\s+/i, "");

  if (dosage) {
    candidate = candidate.slice(0, candidate.toLowerCase().indexOf(dosage.toLowerCase())).trim();
  } else {
    const frequencyMatch = candidate.match(MEDICATION_FREQUENCY_REGEX);
    if (frequencyMatch?.index !== undefined) {
      candidate = candidate.slice(0, frequencyMatch.index).trim();
    }
  }

  candidate = candidate
    .replace(/\b(?:po|oral|tablet|tablets|capsule|capsules|cap|caps|tab|solution|suspension|inject(?:ion|able)?)\b.*$/i, "")
    .replace(/[,:;.\-]+$/, "")
    .trim();

  return toDisplayText(candidate);
}

function isPlausibleMedicationName(name: string): boolean {
  if (!name) return false;

  const tokens = name.split(/\s+/).filter(Boolean);
  if (tokens.length === 0 || tokens.length > 4) return false;

  return !tokens.every((token) => GENERIC_MEDICATION_STOP_WORDS.has(token.toLowerCase()));
}

function buildMedicationCandidatesFromSegment(
  segment: MedicalDocumentEvidenceSegmentRow
): AutoGeneratedCandidate[] {
  const text = segment.normalized_text || segment.quoted_text;
  const labelLower = segment.section_label?.toLowerCase() ?? "";
  const medicationContext =
    /medication|meds|prescription|pharmacy|rx/.test(labelLower) ||
    /\b(?:medications?|tablet|capsule|capsules|dose|dosage|mg|mcg|ml|prn|as needed|daily)\b/i
      .test(text);

  if (!medicationContext) {
    return [];
  }

  const lines = splitMedicationLines(text);
  const candidates: AutoGeneratedCandidate[] = [];

  for (const line of lines) {
    if (
      /\b(?:no current medications|none|nkda|allerg(?:y|ies)|diet|procedure|surgery)\b/i.test(line)
    ) {
      continue;
    }

    const dosageMatch = line.match(/\b\d+(?:\.\d+)?\s?(?:mg|mcg|g|ml|mL|units?|iu|IU)\b/);
    const frequencyMatch = line.match(MEDICATION_FREQUENCY_REGEX);
    if (!dosageMatch && !frequencyMatch && !/medication|meds|rx/.test(labelLower)) {
      continue;
    }

    const dosage = dosageMatch ? dosageMatch[0] : null;
    const medicationName = deriveMedicationName(line, dosage);
    if (!isPlausibleMedicationName(medicationName)) {
      continue;
    }

    const reasonMatch = line.match(/\b(?:for|reason)\b\s*[:\-]?\s*([^.;,\n]+)/i);
    const confidenceBase =
      dosage && /medication|meds|rx/.test(labelLower)
        ? 0.92
        : dosage
          ? 0.84
          : 0.76;

    candidates.push({
      category: "medication",
        detail: {
          medication_name: medicationName,
          dosage,
          frequency: frequencyMatch ? frequencyMatch[1].toLowerCase() : null,
          prescribing_reason: reasonMatch ? cleanListToken(reasonMatch[1]) : null,
        gi_side_effects_known: GI_RELEVANT_MEDICATION_HINTS.some((pattern) => pattern.test(line)),
        start_date: extractFirstDate(line),
          end_date: /\b(?:stopped|discontinued|ended|completed)\b/i.test(line)
            ? extractFirstDate(line)
            : null,
          is_current: !/\b(?:stopped|discontinued|ended|completed|former|previously)\b/i.test(line),
        },
        extractionConfidence: mergeCandidateConfidence(segment.confidence_score, confidenceBase),
      extractionNotes: buildAutoCandidateNote(
        segment.section_label,
        `Matched medication entry "${medicationName}"`
      ),
      evidenceKind: inferCandidateEvidenceKind("medication"),
      evidenceSegmentId: segment.id,
      pageNumber: segment.page_number,
      citedText: line,
      evidenceConfidence: segment.confidence_score,
    });
  }

  return candidates;
}

function buildCandidatesFromEvidenceSegment(
  segment: MedicalDocumentEvidenceSegmentRow
): AutoGeneratedCandidate[] {
  return [
    ...buildDiagnosisCandidatesFromSegment(segment),
    ...buildMedicationCandidatesFromSegment(segment),
    ...buildProcedureCandidatesFromSegment(segment),
    ...buildAllergyCandidatesFromSegment(segment),
    ...buildDietGuidanceCandidatesFromSegment(segment),
    ...buildRedFlagCandidatesFromSegment(segment),
  ];
}

async function fetchAutoEvidenceSegments(
  supabaseAdmin: ReturnType<typeof createClient>,
  intake: MedicalDocumentIntakeRow
): Promise<MedicalDocumentEvidenceSegmentRow[]> {
  const { data, error } = await supabaseAdmin
    .from("medical_document_evidence_segments")
    .select("*")
    .eq("document_intake_id", intake.id)
    .eq("user_id", intake.user_id)
    .like("extractor_label", `${AUTO_SEGMENT_LABEL_PREFIX}%`)
    .order("page_number", { ascending: true })
    .order("created_at", { ascending: true });

  if (error) throw error;
  return (data ?? []) as MedicalDocumentEvidenceSegmentRow[];
}

async function syncAutoGeneratedCandidates(
  supabaseAdmin: ReturnType<typeof createClient>,
  intake: MedicalDocumentIntakeRow,
  evidenceSegments: MedicalDocumentEvidenceSegmentRow[],
): Promise<CandidateGenerationSummary> {
  const { data: existingCandidates, error: candidateError } = await supabaseAdmin
    .from("candidate_medical_facts")
    .select("*")
    .eq("user_id", intake.user_id);

  if (candidateError) throw candidateError;

  const { data: activeFacts, error: activeFactError } = await supabaseAdmin
    .from("medical_facts")
    .select("id, user_id, category, confirmation_state, detail, is_active, created_at, updated_at")
    .eq("user_id", intake.user_id)
    .eq("is_active", true)
    .in("confirmation_state", ["confirmed", "user_reported"]);

  if (activeFactError) throw activeFactError;

  const allCandidateRows = (existingCandidates ?? []) as CandidateMedicalFactRow[];
  const existingRows = allCandidateRows.filter(
    (candidate) => candidate.source_document_id === intake.id,
  );
  const sameDocumentSignatures = new Set(
    existingRows.map((candidate) => buildCandidateSignature(candidate.category, candidate.detail)),
  );
  const otherPendingCandidates = allCandidateRows.filter(
    (candidate) =>
      candidate.review_status === "pending_review" &&
      candidate.source_document_id !== intake.id,
  );
  const activeFactRows = (activeFacts ?? []) as MedicalFactRow[];

  const pendingBySignature = new Map<string, CandidateMedicalFactRow>();
  const pendingByMergeKey = new Map<string, CandidateMedicalFactRow[]>();
  for (const candidate of otherPendingCandidates) {
    const signature = buildCandidateSignature(candidate.category, candidate.detail);
    if (!pendingBySignature.has(signature)) {
      pendingBySignature.set(signature, candidate);
    }

    addToLookupMap(
      pendingByMergeKey,
      buildCandidateMergeKey(candidate.category, candidate.detail),
      candidate,
    );
  }

  const activeFactBySignature = new Map<string, MedicalFactRow>();
  const activeFactByMergeKey = new Map<string, MedicalFactRow[]>();
  for (const fact of activeFactRows) {
    const signature = buildCandidateSignature(fact.category, fact.detail);
    if (!activeFactBySignature.has(signature)) {
      activeFactBySignature.set(signature, fact);
    }

    addToLookupMap(
      activeFactByMergeKey,
      buildCandidateMergeKey(fact.category, fact.detail),
      fact,
    );
  }

  const generatedBySignature = new Map<string, AutoGeneratedCandidate>();

  for (const segment of evidenceSegments) {
    for (const candidate of buildCandidatesFromEvidenceSegment(segment)) {
      const signature = buildCandidateSignature(candidate.category, candidate.detail);
      if (sameDocumentSignatures.has(signature)) continue;

      const current = generatedBySignature.get(signature);
      if (!current || candidate.extractionConfidence > current.extractionConfidence) {
        generatedBySignature.set(signature, candidate);
      }
    }
  }

  let pendingCreatedCount = 0;
  let mergedCreatedCount = 0;
  let conflictFlaggedCount = 0;

  for (const candidate of generatedBySignature.values()) {
    const signature = buildCandidateSignature(candidate.category, candidate.detail);
    const mergeKey = buildCandidateMergeKey(candidate.category, candidate.detail);
    const exactActiveFact = activeFactBySignature.get(signature) ?? null;
    const exactPendingCandidate = pendingBySignature.get(signature) ?? null;
    const overlappingActiveFact =
      mergeKey
        ? (activeFactByMergeKey.get(mergeKey) ?? []).find(
            (fact) => buildCandidateSignature(fact.category, fact.detail) !== signature,
          ) ?? null
        : null;
    const overlappingPendingCandidate =
      mergeKey
        ? (pendingByMergeKey.get(mergeKey) ?? []).find(
            (row) => buildCandidateSignature(row.category, row.detail) !== signature,
          ) ?? null
        : null;

    let reviewStatus: CandidateMedicalFactRow["review_status"] = "pending_review";
    let reviewedAt: string | null = null;
    let promotedFactId: string | null = null;
    let extractionNotes = candidate.extractionNotes;

    if (exactActiveFact) {
      reviewStatus = "merged";
      reviewedAt = new Date().toISOString();
      promotedFactId = exactActiveFact.id;
      extractionNotes = appendStructuredCandidateNote(
        extractionNotes,
        AUTO_MERGE_NOTE_PREFIX,
        createMergeResolutionNote(candidate.category, candidate.detail, "active_fact"),
      );
    } else if (exactPendingCandidate) {
      reviewStatus = "merged";
      reviewedAt = new Date().toISOString();
      extractionNotes = appendStructuredCandidateNote(
        extractionNotes,
        AUTO_MERGE_NOTE_PREFIX,
        createMergeResolutionNote(candidate.category, candidate.detail, "pending_candidate"),
      );
    } else if (overlappingActiveFact) {
      extractionNotes = appendStructuredCandidateNote(
        extractionNotes,
        AUTO_CONFLICT_NOTE_PREFIX,
        createConflictResolutionNote(candidate.category, candidate.detail, "active_fact"),
      );
      conflictFlaggedCount += 1;
    } else if (overlappingPendingCandidate) {
      extractionNotes = appendStructuredCandidateNote(
        extractionNotes,
        AUTO_CONFLICT_NOTE_PREFIX,
        createConflictResolutionNote(candidate.category, candidate.detail, "pending_candidate"),
      );
      conflictFlaggedCount += 1;
    }

    const { data: insertedCandidate, error: insertCandidateError } = await supabaseAdmin
      .from("candidate_medical_facts")
      .insert({
        user_id: intake.user_id,
        category: candidate.category,
        detail: candidate.detail,
        extraction_source: "document_extraction",
        source_document_id: intake.id,
        extraction_confidence: candidate.extractionConfidence,
        extraction_notes: extractionNotes,
        review_status: reviewStatus,
        reviewed_at: reviewedAt,
        promoted_fact_id: promotedFactId,
      })
      .select("id")
      .maybeSingle();

    if (insertCandidateError) throw insertCandidateError;
    if (!insertedCandidate || typeof insertedCandidate !== "object" || !("id" in insertedCandidate)) {
      continue;
    }

    const { error: evidenceError } = await supabaseAdmin
      .from("candidate_medical_fact_evidence")
      .insert({
        user_id: intake.user_id,
        candidate_medical_fact_id: String(insertedCandidate.id),
        document_intake_id: intake.id,
        evidence_segment_id: candidate.evidenceSegmentId,
        evidence_kind: candidate.evidenceKind,
        page_number: candidate.pageNumber,
        cited_text: candidate.citedText,
        confidence_score: candidate.evidenceConfidence ?? candidate.extractionConfidence,
      });

    if (evidenceError) throw evidenceError;

    if (reviewStatus === "merged") {
      mergedCreatedCount += 1;
    } else {
      pendingCreatedCount += 1;
    }
  }

  return {
    pendingCreatedCount,
    mergedCreatedCount,
    conflictFlaggedCount,
    totalCount: existingRows.length + pendingCreatedCount + mergedCreatedCount,
  };
}

function countPdfPages(rawText: string): number | null {
  const pageMatches = rawText.match(/\/Type\s*\/Page\b/g);
  return pageMatches?.length ? pageMatches.length : null;
}

function latin1StringToBytes(value: string): Uint8Array {
  const bytes = new Uint8Array(value.length);
  for (let index = 0; index < value.length; index += 1) {
    bytes[index] = value.charCodeAt(index) & 0xff;
  }
  return bytes;
}

async function tryDecompressStream(bytes: Uint8Array): Promise<Uint8Array | null> {
  for (const format of ["deflate", "deflate-raw"]) {
    try {
      const blob = new Blob([bytes]);
      const stream = blob.stream().pipeThrough(new DecompressionStream(format as never));
      const buffer = await new Response(stream).arrayBuffer();
      return new Uint8Array(buffer);
    } catch {
      // Try the next format.
    }
  }

  return null;
}

function decodePdfLiteralString(literal: string): string {
  const source = literal.startsWith("(") && literal.endsWith(")")
    ? literal.slice(1, -1)
    : literal;

  let result = "";
  for (let index = 0; index < source.length; index += 1) {
    const char = source[index];

    if (char !== "\\") {
      result += char;
      continue;
    }

    const next = source[index + 1];
    if (!next) break;

    if (/[0-7]/.test(next)) {
      let octal = next;
      let consumed = 1;

      while (
        consumed < 3 &&
        index + 1 + consumed < source.length &&
        /[0-7]/.test(source[index + 1 + consumed])
      ) {
        octal += source[index + 1 + consumed];
        consumed += 1;
      }

      result += String.fromCharCode(parseInt(octal, 8));
      index += consumed;
      continue;
    }

    switch (next) {
      case "n":
        result += "\n";
        break;
      case "r":
        result += "\r";
        break;
      case "t":
        result += "\t";
        break;
      case "b":
        result += "\b";
        break;
      case "f":
        result += "\f";
        break;
      case "(":
      case ")":
      case "\\":
        result += next;
        break;
      case "\n":
      case "\r":
        break;
      default:
        result += next;
        break;
    }

    index += 1;
  }

  return result;
}

function collectPdfLiteralStrings(content: string): string[] {
  const decoded: string[] = [];
  let depth = 0;
  let current = "";
  let escaping = false;

  for (let index = 0; index < content.length; index += 1) {
    const char = content[index];

    if (depth === 0) {
      if (char === "(") {
        depth = 1;
        current = "(";
      }
      continue;
    }

    current += char;

    if (escaping) {
      escaping = false;
      continue;
    }

    if (char === "\\") {
      escaping = true;
      continue;
    }

    if (char === "(") {
      depth += 1;
      continue;
    }

    if (char === ")") {
      depth -= 1;

      if (depth === 0) {
        decoded.push(decodePdfLiteralString(current));
        current = "";
      }
    }
  }

  return decoded;
}

function extractPdfTextFromContent(content: string): string {
  const textBlocks = Array.from(content.matchAll(/BT([\s\S]*?)ET/g));
  const segments = textBlocks.length > 0
    ? textBlocks.map((match) => match[1])
    : [content];

  const strings = segments.flatMap((segment) => collectPdfLiteralStrings(segment));
  return normalizeExtractedText(strings.join("\n"));
}

async function extractPdfText(buffer: Uint8Array): Promise<ExtractionResult> {
  const rawPdfText = new TextDecoder("latin1").decode(buffer);
  const collectedTexts: string[] = [];

  const streamRegex = /<<([\s\S]*?)>>\s*stream\r?\n([\s\S]*?)\r?\nendstream/g;
  let streamMatch: RegExpExecArray | null;

  while ((streamMatch = streamRegex.exec(rawPdfText)) !== null) {
    const dictText = streamMatch[1];
    const streamText = streamMatch[2];
    let contentText = streamText;

    if (/\/FlateDecode\b/.test(dictText)) {
      const decompressed = await tryDecompressStream(latin1StringToBytes(streamText));
      if (decompressed) {
        contentText = new TextDecoder("latin1").decode(decompressed);
      }
    }

    const extracted = extractPdfTextFromContent(contentText);
    if (extracted) {
      collectedTexts.push(extracted);
    }
  }

  if (collectedTexts.length === 0) {
    const fallbackText = extractPdfTextFromContent(rawPdfText);
    if (fallbackText) {
      collectedTexts.push(fallbackText);
    }
  }

  const text = normalizeExtractedText(collectedTexts.join("\n\n"));
  if (!text) {
    throw new ExtractionFailure(
      "This PDF appears scanned, image-based, or encoded in a way the current extractor could not read. Manual review remains available until OCR support is added.",
      true,
    );
  }

  return {
    text,
    pageCount: countPdfPages(rawPdfText) ?? 1,
    extractorLabel: "pdf_text_heuristic",
    signalConfidence: 0.78,
  };
}

function decodeXmlEntities(value: string): string {
  return value
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, "\"")
    .replace(/&apos;/g, "'")
    .replace(/&#160;/g, " ")
    .replace(/&#x([0-9a-f]+);/gi, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#([0-9]+);/g, (_, decimal) => String.fromCodePoint(parseInt(decimal, 10)));
}

function convertDocxXmlToText(xml: string): string {
  const withBreaks = xml
    .replace(/<\/w:p>/g, "\n")
    .replace(/<w:tab\/>/g, "\t")
    .replace(/<w:br[^>]*\/>/g, "\n")
    .replace(/<\/w:tr>/g, "\n")
    .replace(/<\/w:tbl>/g, "\n\n");

  const withoutTags = withBreaks.replace(/<[^>]+>/g, " ");
  return normalizeExtractedText(decodeXmlEntities(withoutTags));
}

function readDocxPageCount(zipEntries: Record<string, Uint8Array>): number | null {
  const appXml = zipEntries["docProps/app.xml"];
  if (!appXml) return null;

  const xml = strFromU8(appXml);
  const pagesMatch = xml.match(/<Pages>(\d+)<\/Pages>/i);
  if (!pagesMatch) return null;

  const pages = Number(pagesMatch[1]);
  return Number.isFinite(pages) && pages > 0 ? pages : null;
}

async function extractDocxText(buffer: Uint8Array): Promise<ExtractionResult> {
  let zipEntries: Record<string, Uint8Array>;

  try {
    zipEntries = unzipSync(buffer);
  } catch {
    throw new ExtractionFailure(
      "The DOCX file could not be opened for text extraction. Manual review remains available.",
      true,
    );
  }

  const xmlPaths = Object.keys(zipEntries)
    .filter((path) =>
      /^word\/(document|header\d+|footer\d+|footnotes|endnotes)\.xml$/i.test(path)
    )
    .sort();

  const xmlTexts = xmlPaths
    .map((path) => convertDocxXmlToText(strFromU8(zipEntries[path])))
    .filter(Boolean);

  const text = normalizeExtractedText(xmlTexts.join("\n\n"));
  if (!text) {
    throw new ExtractionFailure(
      "The DOCX file did not contain readable text for the current extractor. Manual review remains available.",
      true,
    );
  }

  return {
    text,
    pageCount: readDocxPageCount(zipEntries) ?? 1,
    extractorLabel: "docx_xml",
    signalConfidence: 0.9,
  };
}

async function extractPlainText(blob: Blob): Promise<ExtractionResult> {
  const text = normalizeExtractedText(await blob.text());

  if (!text) {
    throw new ExtractionFailure(
      "The uploaded text document did not contain extractable text. Manual review remains available.",
      true,
    );
  }

  return {
    text,
    pageCount: 1,
    extractorLabel: "plain_text",
    signalConfidence: 0.98,
  };
}

function getUnsupportedFormatMessage(intake: MedicalDocumentIntakeRow): string {
  if (isImageIntake(intake)) {
    return "Image OCR is not enabled yet. Manual review remains available until OCR support is added.";
  }

  if (isLegacyDocIntake(intake)) {
    return "Legacy .doc extraction is not enabled yet. Please continue with manual review or re-export as DOCX/PDF when possible.";
  }

  return "Automatic extraction is not available for this file type yet. Manual review remains available.";
}

async function extractMedicalDocument(
  intake: MedicalDocumentIntakeRow,
  fileBlob: Blob
): Promise<ExtractionResult> {
  if (isTextIntake(intake)) {
    return extractPlainText(fileBlob);
  }

  const buffer = new Uint8Array(await fileBlob.arrayBuffer());

  if (isPdfIntake(intake)) {
    return extractPdfText(buffer);
  }

  if (isDocxIntake(intake)) {
    return extractDocxText(buffer);
  }

  throw new ExtractionFailure(getUnsupportedFormatMessage(intake), false);
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return jsonResponse(405, {
      success: false,
      error: "Method not allowed",
    });
  }

  const supabaseUrl = Deno.env.get("SUPABASE_URL");
  const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

  if (!supabaseUrl || !serviceRoleKey) {
    return jsonResponse(500, {
      success: false,
      error: "Supabase edge function environment is not configured",
    });
  }

  const authHeader = req.headers.get("Authorization");
  const accessToken = authHeader?.replace(/^Bearer\s+/i, "").trim() ?? "";

  if (!accessToken) {
    return jsonResponse(401, {
      success: false,
      error: "Missing authorization token",
    });
  }

  const supabaseAdmin = createClient(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const {
    data: { user },
    error: authError,
  } = await supabaseAdmin.auth.getUser(accessToken);

  if (authError || !user) {
    return jsonResponse(401, {
      success: false,
      error: "Unable to authenticate document extraction request",
    });
  }

  let intakeId = "";
  try {
    const body = await req.json();
    intakeId = typeof body?.intake_id === "string" ? body.intake_id : "";
  } catch {
    return jsonResponse(400, {
      success: false,
      error: "Invalid JSON body",
    });
  }

  if (!intakeId) {
    return jsonResponse(400, {
      success: false,
      error: "Missing intake_id",
    });
  }

  const { data: intakeData, error: intakeError } = await supabaseAdmin
    .from("medical_document_intakes")
    .select("*")
    .eq("id", intakeId)
    .eq("user_id", user.id)
    .maybeSingle();

  if (intakeError) {
    return jsonResponse(500, {
      success: false,
      error: intakeError.message,
    });
  }

  if (!intakeData) {
    return jsonResponse(404, {
      success: false,
      error: "Document intake not found",
    });
  }

  const intake = intakeData as MedicalDocumentIntakeRow;

  const { data: existingSegmentRows, error: existingSegmentError } = await supabaseAdmin
    .from("medical_document_evidence_segments")
    .select("id", { count: "exact" })
    .eq("document_intake_id", intake.id)
    .eq("user_id", user.id)
    .like("extractor_label", `${AUTO_SEGMENT_LABEL_PREFIX}%`);

  if (existingSegmentError) {
    return jsonResponse(500, {
      success: false,
      error: existingSegmentError.message,
    });
  }

  const existingSegmentCount = existingSegmentRows?.length ?? 0;

  if (intake.extraction_status === "completed" && intake.extracted_text && existingSegmentCount === 0) {
    const backfillExtraction: ExtractionResult = {
      text: intake.extracted_text,
      pageCount: intake.page_count ?? 1,
      extractorLabel: "backfill_existing_text",
      signalConfidence: 0.88,
    };

    await persistEvidenceSegments(supabaseAdmin, intake, backfillExtraction);
    const evidenceSegments = await fetchAutoEvidenceSegments(supabaseAdmin, intake);
    const candidateSummary = await syncAutoGeneratedCandidates(
      supabaseAdmin,
      intake,
      evidenceSegments,
    );

    const refreshedIntake = await updateIntake(supabaseAdmin, intake.id, {
      candidate_count: candidateSummary.totalCount,
      intake_status: "review_ready",
      extraction_status: "completed",
    });

    return jsonResponse(200, {
      success: true,
      intake: refreshedIntake,
      extraction_supported: true,
      message:
        candidateSummary.pendingCreatedCount > 0 ||
        candidateSummary.mergedCreatedCount > 0 ||
        candidateSummary.conflictFlaggedCount > 0
          ? `Evidence segments were built from the existing extracted text. ${buildCandidateSummaryMessage(
              candidateSummary,
              "",
            )}`
          : "Evidence segments were built from the existing extracted text. No auto-generated candidates were found, so manual review remains available.",
    });
  }

  if (intake.extraction_status === "completed" && intake.extracted_text && existingSegmentCount > 0) {
    const evidenceSegments = await fetchAutoEvidenceSegments(supabaseAdmin, intake);
    const candidateSummary = await syncAutoGeneratedCandidates(
      supabaseAdmin,
      intake,
      evidenceSegments,
    );

    const refreshedIntake = await updateIntake(supabaseAdmin, intake.id, {
      candidate_count: candidateSummary.totalCount,
      intake_status: "review_ready",
      extraction_status: "completed",
    });

    return jsonResponse(200, {
      success: true,
      intake: refreshedIntake,
      extraction_supported: true,
      message:
        candidateSummary.pendingCreatedCount > 0 ||
        candidateSummary.mergedCreatedCount > 0 ||
        candidateSummary.conflictFlaggedCount > 0
          ? `Existing extracted evidence was refreshed. ${buildCandidateSummaryMessage(
              candidateSummary,
              "",
            )}`
          : candidateSummary.totalCount > 0
            ? "Document extraction and reviewable candidates are already available."
            : "Existing extracted evidence was refreshed, but no auto-generated candidates were found. Manual review remains available.",
    });
  }

  const processingIntake = await updateIntake(supabaseAdmin, intake.id, {
    intake_status: "processing",
    extraction_status: "processing",
    extraction_error: null,
  });

  if (!processingIntake.storage_bucket || !processingIntake.storage_path) {
    const failedIntake = await updateIntake(supabaseAdmin, intake.id, {
      intake_status: "review_ready",
      extraction_status: "failed",
      extraction_error:
        "This intake does not have a stored document artifact. Manual review remains available.",
    });

    return jsonResponse(200, {
      success: true,
      intake: failedIntake,
      extraction_supported: false,
      message: failedIntake.extraction_error,
    });
  }

  const { data: fileBlob, error: downloadError } = await supabaseAdmin.storage
    .from(processingIntake.storage_bucket)
    .download(processingIntake.storage_path);

  if (downloadError || !fileBlob) {
    const failedIntake = await updateIntake(supabaseAdmin, intake.id, {
      intake_status: "review_ready",
      extraction_status: "failed",
      extraction_error: `Failed to download the stored document for extraction. ${downloadError?.message ?? ""}`.trim(),
    });

    return jsonResponse(200, {
      success: true,
      intake: failedIntake,
      extraction_supported: true,
      message: failedIntake.extraction_error,
    });
  }

  try {
    const extraction = await extractMedicalDocument(processingIntake, fileBlob);
    await persistEvidenceSegments(supabaseAdmin, processingIntake, extraction);
    const evidenceSegments = await fetchAutoEvidenceSegments(supabaseAdmin, processingIntake);
    const candidateSummary = await syncAutoGeneratedCandidates(
      supabaseAdmin,
      processingIntake,
      evidenceSegments,
    );

    const completedIntake = await updateIntake(supabaseAdmin, intake.id, {
      intake_status: "review_ready",
      extraction_status: "completed",
      extraction_error: null,
      extracted_text: extraction.text,
      extracted_at: new Date().toISOString(),
      page_count: extraction.pageCount,
      candidate_count: candidateSummary.totalCount,
    });

    return jsonResponse(200, {
      success: true,
      intake: completedIntake,
      extraction_supported: true,
      message:
        candidateSummary.pendingCreatedCount > 0 ||
        candidateSummary.mergedCreatedCount > 0 ||
        candidateSummary.conflictFlaggedCount > 0
          ? `Document extraction completed and evidence segments are ready. ${buildCandidateSummaryMessage(
              candidateSummary,
              "",
            )}`
          : "Document extraction completed and evidence segments are ready for review. No auto-generated candidates were found, so manual review remains available.",
    });
  } catch (error) {
    const extractionSupported =
      error instanceof ExtractionFailure ? error.extractionSupported : true;
    const message =
      error instanceof Error
        ? error.message
        : "Document extraction failed. Manual review remains available.";

    const failedIntake = await updateIntake(supabaseAdmin, intake.id, {
      intake_status: "review_ready",
      extraction_status: "failed",
      extraction_error: message,
    });

    return jsonResponse(200, {
      success: true,
      intake: failedIntake,
      extraction_supported: extractionSupported,
      message,
    });
  }
});

});
